
version: "3.7"
services:
    blackboxexporter:
        container_name: blackboxexporter
        hostname: blackboxexporter.weave.local
        network_mode: bridge
        init: true
        image:  prom/blackbox-exporter:latest
        # ports:
        #     - 9115:9115
        volumes:
            - ${OVERNODE_ETC}/prometheus/blackboxexporter/config.yml:/etc/blackboxexporter/blackboxexporter-config.yaml
        env_file:
            - prometheus/blackboxexporter.md5env
        restart: unless-stopped
        command:
            - --config.file=/etc/blackboxexporter/blackboxexporter-config.yaml
        logging:
            driver: loki
            options:
                loki-url: "http://localhost:3100/loki/api/v1/push"
                max-size: 20m
                max-file: "5"

