placements:
  default:
    services:
      sleep-server:
        seeds: 1
        cpus: 1
        ports:
          9042: 9042
      sleep-client:
        seeds: 1
        cpus: 1

services:
  cassandra:
    # TODO enable a service to declare public IP address
    image: clusterlite/cassandra:3.10
    environment:
      # TODO clusterlite node installation should get cluster name, rack, datacenter names in arguments
      CASSANDRA_CLUSTER_NAME: Clusterlite-Example
      CASSANDRA_DC: DC1-Clusterlite
      CASSANDRA_RACK: Rack1-Demo
      CASSANDRA_AUTO_BOOTSTRAP: "false"
    options: --env SOMEOTHEROPTIONS=EXAMPLE
  telegraf:
    image: clusterlite/telegraf:2.0.0
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
    volumes:
      /var/run: /rootfs/var/run:ro
      /var/run/docker.sock: /var/run/docker.sock:ro
      /sys: /rootfs/sys:ro
      /proc: /rootfs/proc:ro
    inspect: ps -ef
    probe: ps -ef
    repair: du /data
    stateless: true
  sleep-server:
    image: alpine:3.6
    options: -p 80:80
    command:
    - sleep
    - 5000
    probe: ps -ef
    repair: du /data
    logging:
      driver: json-file
      options:
        max-size: 200m
        max-file: "3"
  sleep-client:
    image: alpine:3.6
    command:
    - sleep
    - 2000
    dependencies:
      sleep-server:
        env: SLEEP_SERVER_SERVICE_NAME
    probe: ps -ef
    repair: du /data
    stateless: true
