#
# Sample Clusterlite configuration
#
placements:
  default:
    services:
      sleep-server:
        memory: 1024m # can be also percentage of total on a host
        memory-swap: 1024m
        memory-swappiness: 50
        kernel-memory: 1024m
        blkio-weight: 300
        cpus: 1
        cpuset-cpus: 0,3
        cpu-shares: 1024
      sleep-client:
        seeds: 3
        cpus: 1
      telegraf:
        memory: 256m
  monitored-node:
    inherits: default(0.7) # reduces allocated resources for the parent to 70%
    services:
      telegraf:
        memory: 256m
  # for the future
#  autoscalable-node: # will support commands: scale, scaleout, scalein
#    services:
#      custom_service:
#        #instances: 0 # default initial number of instances in total, or 1x - number of instances per matched node
#        cpus: 1

services:
  telegraf:
    image: webintrinsics/telegraf:2.0.0
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
    volumes:
      /var/run: /rootfs/var/run:ro
      /var/run/docker.sock: /var/run/docker.sock:ro
      /sys: /rootfs/sys:ro
      /proc: /rootfs/proc:ro
    inspect: ps -ef
    probe: ps -ef
    repair: du /data
    stateless: true # if true does not mount /data volume and use automatic IP address pool
  sleep-server:
    image: webintrinsics/base:2.0.0
    options: -p 80:80
    command: sleep 2000
    probe: ps -ef
    repair: du /data
  sleep-client:
    image: webintrinsics/base:2.0.0
    command: sleep 2000
    dependencies:
    - sleep-server
    probe: ps -ef
    repair: du /data
    stateless: true # if true does not mount /data volume and use automatic IP address pool
