
version: "3.7"
services:
    graylog-es:
        container_name: graylog-es
        hostname: graylog-es.weave.local
        network_mode: bridge
        init: true
        image:  docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.5
        environment:
            - http.host=0.0.0.0
            - transport.host=localhost
            - network.host=0.0.0.0
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        volumes:
            - graylog-es-data:/usr/share/elasticsearch/data
        restart: always
        ulimits:
            memlock:
                soft: -1
                hard: -1
volumes:
    graylog-es-data:
        name: graylog-es-data