version: '3.7'
services:
    service-1:
        container_name: service-1
        hostname: zookeeper.weave.local
        init: true
        # pid: "host"
        image: ubuntu:16.04
        deploy:
            resources:
                limits:
                    cpus: "0.2"
        environment:
            WEAVE_CIDR: 10.32.19.${OVERNODE_ID}/12
            NODE_ID: ${OVERNODE_ID}
            # CONTAINER_IP: 10.32.0.1.1
            # CONTAINER_NAME: {SERVICE_NAME}
            # CONTAINER_ID: {CONTAINER_ID}
            # OVERNODE_ID: {OVERNODE_ID}
            SERVICE_NAME: zookeeper.cade.local
            DOCKER_NODE_ID: "{{.Node.ID}}"
            DOCKER_NODE_HOSTNAME: "{{.Node.Hostname}}"
        volumes:
            - ${OVERNODE_ETC}:/data
            # - /data/zookeeper/data:/data
            # - /usr/bin/docker:/docker
            # - /var/run/docker.sock:/var/run/docker.sock
        entrypoint: bash /data/service1-entrypoint.sh aab
        restart: always
        network_mode: bridge
        healthcheck:
            test: ["CMD", "false"]
            interval: 20s
            timeout: 100s
            retries: 3
            start_period: 10s