
version: "3.7"
services:
    promtail:
        container_name: promtail
        hostname: promtail-${OVERNODE_ID}.weave.local
        network_mode: bridge
        init: true
        image:  grafana/promtail:latest
        volumes:
            - ${OVERNODE_ETC}/loki/promtail/config.yml:/etc/promtail/promtail-config.yaml
            - /var/log:/var/log
            - promtail-data:/data
        env_file:
            - loki/promtail.md5env
        restart: unless-stopped
        command:
            - --config.file=/etc/promtail/promtail-config.yaml
            - --client.external-labels=host=${OVERNODE_TARGET}
        logging:
            driver: json-file
            options:
                max-size: 20m
                max-file: "5"

volumes:
    promtail-data:
        name: promtail-data