version: "3.7"
services:
    loki:
        container_name: loki
        hostname: loki.weave.local
        network_mode: bridge
        init: true
        image:  grafana/loki:latest
        restart: unless-stopped
        command: -config.file=/etc/loki/local-config.yaml
        volumes:
            - loki-data:/loki
        logging:
            driver: json-file
            options:
                max-size: 20m
                max-file: "5"

volumes:
    loki-data:
        name: loki-data
