version: '3.7'
services:
    nginx:
        container_name: nginx
        hostname: nginx.weave.local
        init: true
        ports:
            - 80:80
        image: nginx
        restart: always
        network_mode: bridge