
version: "3.7"
services:
    kapacitor:
        container_name: kapacitor
        hostname: kapacitor.weave.local
        network_mode: bridge
        init: true
        image:  kapacitor:alpine
        environment:
            KAPACITOR_REPORTING_ENABLED: "false"
            KAPACITOR_INFLUXDB_NAME: influxdb
            KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
        volumes:
            - kapacitor-data:/var/lib/kapacitor
        restart: unless-stopped

volumes:
    kapacitor-data:
        name: kapacitor-data
