
version: "3.7"
services:
    telegraf:
        container_name: telegraf
        hostname: telegraf-${OVERNODE_ID}.weave.local
        network_mode: bridge
        dns: ${OVERNODE_BRIDGE_IP}
        init: true
        image:  telegraf:alpine
        ports:
            - 127.0.0.1:6514:6514/udp
        environment:
            HOST_PROC: /host/proc
        env_file:
            - telegraf.conf.md5env
        volumes:
            - ${OVERNODE_ETC}/telegraf.conf:/etc/telegraf/telegraf.conf:ro
            - /var/run/docker.sock:/var/run/docker.sock
            - /proc:/host/proc:ro
        restart: unless-stopped
