#
# Sample Clusterlite configuration to deploy Cassandra service
#
placements:
  default:
    services:
      cassandra:
        seeds: 1
        ports:
          9042: 9042

services:
  cassandra:
    image: clusterlite/cassandra:3.9
    environment:
      # TODO clusterlite node installation should get cluster name, rack, datacenter names in arguments
      CASSANDRA_CLUSTER_NAME: Clusterlite Cassandra Example
      CASSANDRA_DC: DC1-Clusterlite
      CASSANDRA_RACK: Rack1-Demo
