version: "3.7"
services:
    grafana-proxy:
        container_name: grafana-proxy
        hostname: grafana-proxy.weave.local
        image: nginx:alpine
        network_mode: bridge
        init: true
        ports:
            - 4431:443
        restart: unless-stopped
        environment:
            - RESOLVER_IP=${OVERNODE_BRIDGE_IP}
            # - UPSTREAM_IP=10.32.${OVERNODE_CONFIG_GRAFANA_ID}.${OVERNODE_ID}
            - UPSTREAM_IP=grafana
        env_file:
            - grafana/proxy.md5env
        volumes:
            - ${OVERNODE_ETC}/grafana/proxy/.htpasswd:/etc/nginx/.htpasswd:ro
            - ${OVERNODE_ETC}/grafana/proxy/nginx.conf:/etc/nginx/nginx.conf:ro
            - ${OVERNODE_ETC}/grafana/proxy/proxy.conf.template:/etc/nginx/templates/proxy.conf.template:ro
            - ${OVERNODE_ETC}/grafana/proxy/cert.crt:/etc/nginx/cert.crt:ro
            - ${OVERNODE_ETC}/grafana/proxy/cert.key:/etc/nginx/cert.key:ro
        logging:
            driver: loki
            options:
                loki-url: "http://localhost:3100/loki/api/v1/push"
                max-size: 20m
                max-file: "5"
