
version: "3.7"
services:
    alertmanager:
        container_name: alertmanager
        hostname: alertmanager-${OVERNODE_ID}.weave.local
        network_mode: bridge
        init: true
        image:  prom/alertmanager:latest
        # ports:
        #     - 9093:9093
        volumes:
            - ${OVERNODE_ETC}/prometheus/alertmanager/config.yml:/etc/alertmanager/alertmanager-config.yaml
            - alertmanager-data:/data
        restart: unless-stopped
        env_file:
            - prometheus/alertmanager.md5env
        command:
            - --config.file=/etc/alertmanager/alertmanager-config.yaml
            - --storage.path=/data
        logging:
            driver: loki
            options:
                loki-url: "http://localhost:3100/loki/api/v1/push"
                max-size: 20m
                max-file: "5"

volumes:
    alertmanager-data:
        name: alertmanager-data
