
version: "3.7"
services:
    prometheus:
        container_name: prometheus
        hostname: prometheus.weave.local
        network_mode: bridge
        init: true
        image:  prom/prometheus:latest
        user: root # default user is not roor, but the volume created requires root per
        # ports:
        #     - 8888:9090 # remove if you would not like to expose the service on the host interface
        environment:
            WEAVE_CIDR: 10.32.${OVERNODE_CONFIG_PROMETHEUS_ID}.${OVERNODE_ID}/12
        env_file:
            - prometheus/service.md5env
        volumes:
            - ${OVERNODE_ETC}/prometheus/service/config.yml:/etc/prometheus/prometheus.yml:ro
            - ${OVERNODE_ETC}/prometheus/service/alert.rules:/etc/prometheus/alert.rules:ro
            - prometheus-data:/data
        restart: unless-stopped
        command:
            - --config.file=/etc/prometheus/prometheus.yml
            - --storage.tsdb.path=/data
        logging:
            driver: loki
            options:
                loki-url: "http://localhost:3100/loki/api/v1/push"
                max-size: 20m
                max-file: "5"

volumes:
    prometheus-data:
        name: prometheus-data
