#
# Sample Cade configuration to deploy InfluxDB service
#
placements:
  default:
    services:
      influxdb:
        ports:
          8083: 8083
          8086: 8086

services:
  influxdb:
    image: cadeworks/influxdb:1.2.2
